http_port 3128
visible_hostname metisa-squid
pid_filename /run/squid/squid.pid

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

http_access allow localhost manager
http_access deny manager

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

http_access deny to_localhost
http_access deny to_linklocal

acl blocked_destinations dst 0.0.0.0/8
acl blocked_destinations dst 10.0.0.0/8
acl blocked_destinations dst 100.64.0.0/10
acl blocked_destinations dst 127.0.0.0/8
acl blocked_destinations dst 169.254.0.0/16
acl blocked_destinations dst 172.16.0.0/12
acl blocked_destinations dst 192.168.0.0/16
acl blocked_destinations dst 224.0.0.0/4
acl blocked_destinations dst 240.0.0.0/4
acl blocked_destinations dst ::1/128
acl blocked_destinations dst fc00::/7
acl blocked_destinations dst fe80::/10
acl blocked_destinations dst ff00::/8

http_access deny blocked_destinations

include /etc/squid/metisa-allow.conf

http_access deny all

cache deny all
access_log stdio:/dev/stdout
cache_log /dev/stderr

shutdown_lifetime 5 seconds