agent_name = "sample_agent"
capabilities = [
    # "interactive",
    "network",
    "internet",
]
dependencies = [
    "requests==2.34.2"
]

[squid_proxy]
allowed_domains = [
  ".example.com"
]
allowed_ip_addresses = []