agent_name = "sample_agent"
capabilities = [
    # "interactive",
    "network",
    "internet",
    "localnet",
    "mcp_client",
]
dependencies = [
    "requests==2.34.2",
    "mcp==2.3.0",
]
environs = [
    "METISA_PROBE_1=hard-coded value",
    "METISA_PROBE_2=${host:METISA_PROBE_2}",
]

[squid_proxy]
allowed_domains = [
  ".example.com",
]
allowed_ip_addresses = []

[haproxy]
backends = [
    { listen_port = 3306, host = "host.docker.internal", port = 3306 },
]

[mcp_server]
tools = [
    "test_tool_2",
    "test_tool_3",
    "get_active_items",
]
resources = [
    "test_resource_2",
]
environs = [
    "SANDBOX_TESTER_MARIADB_CREDENTIALS=${host:SANDBOX_TESTER_MARIADB_CREDENTIALS}",
]